---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - name: Import VPC Setup Variable
     include_vars: vars/bastion_setup

   - name: Create vprofile ec2 key pair
     ec2_key:
       name: vprofile-key
       region: "{{ region }}"
       state: present
     register: keypair_out
 
   - name: Save private key into file bastion-key.pem
     copy:
      content: "{{ keypair_out.key.private_key }}"
      dest: "./bastion-key.pem"
      mode: '0600'
     when: keypair_out.changed

   - name: Create Sec Grp for bastion host
     ec2_group:
       name: Vprofile-Bastion-SG
       description: Security group for vprofile bastion host
       vpc_id: "{{ vpc_id }}"
       region: "{{ region }}"
       rules:
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: "{{ MY_IP }}"
     register: bastion_sg

   - name: Create vprofile bastion host
     ec2:
       key_name: vprofile-key
       group_id: "{{ bastion_sg.group_id }}"
       instance_type: t2.micro
       image: "{{ bastion_ami }}"
       wait: yes
       wait_timeout: 500
       instance_tags:
         Name: vprofile-bastion-host
         Project: Vprofile
         Owner: DevOps Team
       region: "{{ region }}"
       vpc_subnet_id: "{{ pub_subnet1_id }}"
       assign_public_ip: yes
       exact_count: 1
       count_tag:
          Name: vprofile-bastion-host
          Project: Vprofile
          Owner: DevOps Team
     register: bastion_out