---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - name: Import VPC Setup Variable
     include_vars: vars/vpc_setup

   - name: Import base VPC variables
     include_vars: vars/vpc_setup

   - name: Get VPC info
     amazon.aws.ec2_vpc_net_info:
       region: "{{ region }}"
       filters:
         "tag:Name": "{{ vpc_name }}"
     register: vpc_info

   - name: Set VPC ID
     set_fact:
       vpc_id: "{{ vpc_info.vpcs[0].id }}"
     when: vpc_info.vpcs | length > 0

   - name: Get public subnet 1 info
     amazon.aws.ec2_vpc_subnet_info:
       region: "{{ region }}"
       filters:
         vpc-id: "{{ vpc_id }}"
         "tag:Name": vprofile-pubsub1
     register: pub_subnet1_info

   - name: Set public subnet 1 ID
     set_fact:
       pub_subnet1_id: "{{ pub_subnet1_info.subnets[0].id }}"
     when: pub_subnet1_info.subnets | length > 0

   - name: Ensure required network IDs are available
     assert:
       that:
         - vpc_id is defined
         - pub_subnet1_id is defined
       fail_msg: "Required VPC/Subnet IDs are missing. Ensure VPC and public subnet (tag Name=vprofile-pubsub1) exist."

   - name: Create vprofile ec2 key pair
     amazon.aws.ec2_key:
       name: vprofile-key
       region: "{{ region }}"
       state: present
     register: keypair_out
 
   - name: Save private key into file bastion-key.pem
     copy:
      content: "{{ keypair_out.key.private_key }}"
      dest: "./bastion-key.pem"
      mode: '0600'
     when: keypair_out.changed

   - name: Create Sec Grp for bastion host
     amazon.aws.ec2_security_group:
       name: Vprofile-Bastion-SG
       description: Security group for vprofile bastion host
       vpc_id: "{{ vpc_id }}"
       region: "{{ region }}"
       rules:
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: "{{ MYIP }}"
     register: bastion_sg

   - name: Create vprofile bastion host
     amazon.aws.ec2_instance:
       name: vprofile-bastion-host
       state: running
       key_name: vprofile-key
       security_group: "{{ bastion_sg.group_id }}"
       instance_type: t2.micro
       image_id: "{{ bastion_ami }}"
       wait: yes
       wait_timeout: 500
       tags:
         Name: vprofile-bastion-host
         Project: Vprofile
         Owner: DevOps Team
       region: "{{ region }}"
       vpc_subnet_id: "{{ pub_subnet1_id }}"
       network:
         assign_public_ip: yes
       exact_count: 1
       filters:
         "tag:Name": vprofile-bastion-host
         "tag:Project": Vprofile
         "tag:Owner": DevOps Team
     register: bastion_out