---
- name: Setup Vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
   - name: Import VPC Setup Variable
     include_vars: vars/vpc-output_vars

   - name: import ec2 instance variables
     include_vars: vars/vprostacksetup


   - name: Create keypair
     amazon.aws.ec2_key:
       name: vprofile-key
       region: "{{ region }}"
       state: present
     register: keypair_out

   - name: save private key into loginkey_vpro.pem
     copy:
       content: "{{ keypair_out.key.private_key }}"
       dest: "./loginkey_vpro.pem"
       mode: '0600'
     when: keypair_out.changed

   - name: Create Security Group for Load Balancer
     amazon.aws.ec2_security_group:
        name: vprofile-lb-sg
        description: Security group for vprofile load balancer
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
     register: lb_sg_out


   - name: Create Security Group for Vprofile stack
     amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: Security group for vprofile stack
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ lb_sg_out.group_id }}"
       
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ bastion_sg_id }}"


   - name: Update Security Group with its own sg id
     amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: Security group for vprofile stack
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            group_id: "{{ vprofile_stack_sg_out.group_id }}"

  


