---
- name: Setup Vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Import VPC Setup Variable
      include_vars: vars/vpc-output_vars

    - name: import ec2 instance variables
      include_vars: vars/vprostacksetup

    - name: Create keypair
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{ region }}"
        state: present
      register: keypair_out

    - name: save private key into loginkey_vpro.pem
      copy:
        content: "{{ keypair_out.key.private_key }}"
        dest: "./loginkey_vpro.pem"
        mode: '0600'
      when: keypair_out.changed

    - name: Create Security Group for Load Balancer
      amazon.aws.ec2_security_group:
        name: vprofile-lb-sg
        description: Security group for vprofile load balancer
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: lb_sg_out

    - name: Create Security Group for Vprofile stack
      amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: Security group for vprofile stack
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ lb_sg_out.group_id }}"
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ bastion_sg_id }}"
      register: vprofile_stack_sg_out

    - name: Update Security Group with its own sg id
      amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: Security group for vprofile stack
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_id: "{{ vprofile_stack_sg_out.group_id }}"
          - proto: tcp
            from_port: 5672
            to_port: 5672
            group_id: "{{ vprofile_stack_sg_out.group_id }}"
          - proto: tcp
            from_port: 11211
            to_port: 11211
            group_id: "{{ vprofile_stack_sg_out.group_id }}"

    - name: Creating Nginx web01
      amazon.aws.ec2_instance:
        name: vprofile-web01
        state: running
        key_name: vprofile-key
        instance_type: t2.micro
        image_id: "{{ nginx_ami }}"
        region: "{{ region }}"
        security_group: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        filters:
          "tag:Name": vprofile-web01
        tags:
          Name: vprofile-web01
          Project: Vprofile
          Owner: DevOps Team
      register: web01_out

    - name: Creating tomcat app01
      amazon.aws.ec2_instance:
        name: vprofile-app01
        state: running
        key_name: vprofile-key
        instance_type: t2.micro
        image_id: "{{ tomcat_ami }}"
        region: "{{ region }}"
        security_group: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        filters:
          "tag:Name": vprofile-app01
        tags:
          Name: vprofile-app01
          Project: Vprofile
          Owner: DevOps Team
      register: app01_out

    - name: Creating memcache mc01
      amazon.aws.ec2_instance:
        name: vprofile-mc01
        state: running
        key_name: vprofile-key
        instance_type: t2.micro
        image_id: "{{ memcache_ami }}"
        region: "{{ region }}"
        security_group: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        filters:
          "tag:Name": vprofile-mc01
        tags:
          Name: vprofile-mc01
          Project: Vprofile
          Owner: DevOps Team
      register: mc01_out

    - name: Creating RabbitMQ rmq01
      amazon.aws.ec2_instance:
        name: vprofile-rmq01
        state: running
        key_name: vprofile-key
        instance_type: t2.micro
        image_id: "{{ rmq_ami }}"
        region: "{{ region }}"
        security_group: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        filters:
          "tag:Name": vprofile-rmq01
        tags:
          Name: vprofile-rmq01
          Project: Vprofile
          Owner: DevOps Team
      register: rmq01_out

    - name: Creating Mysql db01
      amazon.aws.ec2_instance:
        name: vprofile-db01
        state: running
        key_name: vprofile-key
        instance_type: t2.micro
        image_id: "{{ mysql_ami }}"
        region: "{{ region }}"
        security_group: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        filters:
          "tag:Name": vprofile-db01
        tags:
          Name: vprofile-db01
          Project: Vprofile
          Owner: DevOps Team
      register: db01_out

    - debug:
      var: db01_out.instances[0].instance_id
 
    - name: Create/Update ELB
      local_action:
        module: ec2_elb_lb
        name: "vprofile-elb"
        region: "{{ region }}"
        state: present
        instance_ids:
          - "{{ web01_out.instances[0].instance_id }}"
        purge_instance_ids: true
        security_group_ids:
          - "{{ lb_sg_out.group_id }}"
        subnets:
          - "{{ pub_subnet1_id }}"
          - "{{ pub_subnet2_id }}"
        listeners:
          - protocol: HTTP
            load_balancer_port: 80
            instance_port: 80

    - name: Insert/Update host IPs in provision-stack/group_vars/hostip
      blockinfile:
        path: provision-stack/group_vars/hostip
        block: |
          web01_ip: "{{ web01_out.instances[0].private_ip_address }}"
          app01_ip: "{{ app01_out.instances[0].private_ip_address }}"
          rmq01_ip: "{{ rmq01_out.instances[0].private_ip_address }}"
          mc01_ip: "{{ mc01_out.instances[0].private_ip_address }}"
          db01_ip: "{{ db01_out.instances[0].private_ip_address }}"


    - name: Copy login key to provision-stack directory
      copy:
        src: "./loginkey_vpro.pem"
        dest: "provision-stack/loginkey_vpro.pem"
        mode: '0400'

    
    - name: Insert/Update Inventory file provision-stack/inventory repo
      blockinfile:
        path: provision-stack/inventory-repo
        block: |
          [webservgrp]
          web01 ansible_host={{ web01_out.instances[0].private_ip_address }}

          [appservgrp]
          app01 ansible_host={{ app01_out.instances[0].private_ip_address }}

          [rmqservgrp]
          rmq01 ansible_host={{ rmq01_out.instances[0].private_ip_address }}

          [mcservgrp]
          mc01 ansible_host={{ mc01_out.instances[0].private_ip_address }}

          [dbservgrp]
          db01 ansible_host={{ db01_out.instances[0].private_ip_address }}

          [control]
          cntl ansible_host=127.0.0.1 ansible_connection=local

          [stack_inst:children]
          webservgrp
          appservgrp
          rmqservgrp
          mcservgrp
          dbservgrp

          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=provision-stack/loginkey_vpro.pem







  


