---
- name: Setup Vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
   - name: Import VPC Setup Variable
     include_vars: vars/vpc-output_vars

   - name: import ec2 instance variables
     include_vars: vars/vprostacksetup


   - name: Create keypair
     amazon.aws.ec2_key:
       name: vprofile-key
       region: "{{ region }}"
       state: present
     register: keypair_out

   - name: save private key into loginkey_vpro.pem
     copy:
       content: "{{ keypair_out.key.private_key }}"
       dest: "./loginkey_vpro.pem"
       mode: '0600'
     when: keypair_out.changed

   - name: Create Security Group for Load Balancer
     amazon.aws.ec2_security_group:
        name: vprofile-lb-sg
        description: Security group for vprofile load balancer
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
     register: lb_sg_out


   - name: Create Security Group for Vprofile stack
     amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: Security group for vprofile stack
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ lb_sg_out.group_id }}"
       
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ bastion_sg_id }}"
     register: vprofile_stack_sg_out


   - name: Update Security Group with its own sg id
     amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: Security group for vprofile stack
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_id: "{{ vprofile_stack_sg_out.group_id }}"
          - proto: tcp
            from_port: 5672
            to_port: 5672
            group_id: "{{ vprofile_stack_sg_out.group_id }}"
          - proto: tcp
            from_port: 11211
            to_port: 11211
            group_id: "{{ vprofile_stack_sg_out.group_id }}"

   - name: Creating Nginx web01
     amazon.aws.ec2:
        key_name: vprofile-key
        instance_type: t2.micro
        image: "{{ nginx_ami }}"
        region: "{{ region }}"
        group_id: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: vprofile-web01
        instance_tags:
          Name: vprofile-web01
          Project: Vprofile
          Owner: DevOps Team
     register: web01_out


   - name: Creating tomcat app01
     amazon.aws.ec2:
        key_name: vprofile-key
        instance_type: t2.micro
        image: "{{ tomcat_ami }}"
        region: "{{ region }}"
        group_id: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: vprofile-app01
        instance_tags:
          Name: vprofile-app01
          Project: Vprofile
          Owner: DevOps Team
     register: app01_out



   - name: Creating memcache mc01
     amazon.aws.ec2:
        key_name: vprofile-key
        instance_type: t2.micro
        image: "{{ memcache_ami }}"
        region: "{{ region }}"
        group_id: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: vprofile-mc01
        instance_tags:
          Name: vprofile-mc01
          Project: Vprofile
          Owner: DevOps Team
     register: mc01_out


   - name: Creating RabbitMQ rmq01
     amazon.aws.ec2:
        key_name: vprofile-key
        instance_type: t2.micro
        image: "{{ rabbitmq_ami }}"
        region: "{{ region }}"
        group_id: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: vprofile-rmq01
        instance_tags:
          Name: vprofile-rmq01
          Project: Vprofile
          Owner: DevOps Team
     register: rmq01_out


   - name: Creating Mysql db01
     amazon.aws.ec2:
        key_name: vprofile-key
        instance_type: t2.micro
        image: "{{ mysql_ami }}"
        region: "{{ region }}"
        group_id: "{{ vprofile_stack_sg_out.group_id }}"
        vpc_subnet_id: "{{ priv_subnet1_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: vprofile-db01
        instance_tags:
          Name: vprofile-db01
          Project: Vprofile
          Owner: DevOps Team
     register: db01_out

   - debug:
      var: db01_out



  


