- name: Set host to ip mapping in /etc/hosts file of all the instances in the stack
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Import VPC setup Variable
      include_vars: group_vars/hostip

    - name: Update hosts file for all the hosts without Python on target
      raw: |
        changed=0
        while IFS= read -r entry; do
          if ! grep -qxF "$entry" /etc/hosts; then
            echo "$entry" >> /etc/hosts
            changed=1
          fi
        done <<'EOF'
        {{ web01_ip }} web01
        {{ app01_ip }} app01
        {{ rmq01_ip }} rmq01
        {{ mc01_ip }} mc01
        {{ db01_ip }} db01
        EOF
        if [ "$changed" -eq 1 ]; then
          echo CHANGED
        fi
      register: hosts_file_update
      changed_when: "'CHANGED' in hosts_file_update.stdout"